### ISSUE TITLE
repeated StructuredProperty field is ignored in response when getting object

### ISSUE THREAD

**Issue by zdenulo** [GoogleCloudPlatform/endpoints-proto-datastore#134] opened 2015-08-14 16:42 UTC
code example and detailed explanation is here https://github.com/zdenulo/epd-error-example

**Comment by dhermes** [comment] 2015-08-17 16:09
Thanks for filing. I confirmed the issue and will hopefully have a fix today. Your fix may work fine, but it seems out of place since the `None` check comes right after `None` is used as a fall-back with `getattr`.

**Comment by dhermes** [comment] 2015-11-19 01:49
FYI this fix is going in as #140. Thanks a lot! I'm closing since #138 also covers it.

**Closed by dhermes** 2015-11-19 01:49 UTC
